# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 01:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 14, 1, 20, 58, 527671), verbose_name='date added'),
        ),
    ]
